# Generated by Django 4.1.1 on 2022-09-12 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.CharField(max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('weightloss', 'Weightloss'), ('muscle gain', 'Muscle Gain'), ('gut health', 'Gut Health'), ('healthy eating', 'Healthy Eating'), ('exercise', 'Exercise')], default='weightloss', max_length=60)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
