# Generated by Django 4.1.1 on 2022-09-18 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=60)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('height', models.IntegerField(blank=True)),
                ('muscle_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('body_fat_mass', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('visceral_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('meal_plan', models.FileField(upload_to="documents/<class 'accounts.models.UserAccount'>/%Y/%m/%d")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='programs.wellnessprogram')),
            ],
        ),
    ]
