# Generated by Django 4.1.1 on 2022-09-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='meal_plan',
            field=models.FileField(upload_to="documents/str(<class 'accounts.models.UserAccount'>)/%Y/%m/%d"),
        ),
    ]
